const API_BASE = window.localStorage.getItem('fanfolio_api_base') || 'http://localhost:8000/api';
const demo = { metrics: { totalCards: 132, publishedCards: 48, activeDrops: 8, redeemedCount: 24680 } };
let state = { view: 'dashboard', cards: [
  {id:'demo-021',title:'방탄소년단 #021',artist:'드림스타',member:'진',rarity:'SR',status:'published',supply:1500},
  {id:'demo-020',title:'방탄소년단 #020',artist:'드림스타',member:'뷔',rarity:'SR',status:'published',supply:1200},
  {id:'demo-019',title:'방탄소년단 #019',artist:'드림스타',member:'정국',rarity:'R',status:'draft',supply:1500},
  {id:'demo-018',title:'방탄소년단 #018',artist:'드림스타',member:'RM',rarity:'N',status:'published',supply:2000}
]};
const app = document.querySelector('#app');
const escapeHtml = (value) => String(value).replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
function layout(){app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">Fanfolio <span>✦</span></div><nav class="nav"><button data-view="dashboard" class="${state.view==='dashboard'?'active':''}">⌂　대시보드</button><button data-view="cards" class="${state.view==='cards'?'active':''}">▦　카드 관리</button><button data-view="batches" class="${state.view==='batches'?'active':''}">⌁　드롭·코드 관리</button><button data-view="settings" class="${state.view==='settings'?'active':''}">⚙　설정</button></nav><div class="account"><strong>관리자</strong>admin@fanfolio.com<button class="logout" id="logout">로그아웃　›</button></div></aside><main class="main"><header class="topbar"><div><p class="eyebrow">Fanfolio 운영 센터</p><h1 class="title">${state.view==='dashboard'?'대시보드':state.view==='cards'?'카드 관리':state.view==='batches'?'드롭·코드 관리':'설정'}</h1></div><div class="top-actions"><span class="status">● 시스템 정상</span><button class="primary" id="refresh">새로고침</button></div></header><section class="view ${state.view==='dashboard'?'active':''}" id="dashboard-view">${dashboardView()}</section><section class="view ${state.view==='cards'?'active':''}" id="cards-view">${cardsView()}</section><section class="view ${state.view==='batches'?'active':''}" id="batches-view">${batchesView()}</section><section class="view ${state.view==='settings'?'active':''}" id="settings-view">${settingsView()}</section></main></div><div class="toast" id="toast"></div>`;bind();}
function dashboardView(){const m=state.metrics||demo.metrics;return `<div class="metrics"><div class="metric"><span class="metric-label">전체 카드</span><div class="metric-value">${m.totalCards||demo.metrics.totalCards}</div><span class="metric-note">전체 등록 카드</span></div><div class="metric"><span class="metric-label">공개 카드</span><div class="metric-value">${m.publishedCards||demo.metrics.publishedCards}</div><span class="metric-note">+8.2% 지난달 대비</span></div><div class="metric"><span class="metric-label">진행 중 드롭</span><div class="metric-value">${m.activeDrops||demo.metrics.activeDrops}</div><span class="metric-note">모집 진행 중</span></div><div class="metric"><span class="metric-label">발급 수</span><div class="metric-value">${(m.redeemedCount||demo.metrics.redeemedCount).toLocaleString()}</div><span class="metric-note">전체 누적</span></div></div><div class="grid-2"><div class="panel"><h2>발급 수 추이 <span class="eyebrow">최근 7일</span></h2><div class="chart">${[30,48,74,39,57,45,72].map((height,i)=>`<div class="bar" style="height:${height}%"><span>${['05.06','05.07','05.08','05.09','05.10','05.11','05.12'][i]}</span></div>`).join('')}</div></div><div class="panel"><h2>카드 공개 상태</h2><div class="donut-wrap"><div class="donut"></div><div class="legend"><span><i></i>공개됨　48 (36.4%)</span><span><i class="gray"></i>비공개　84 (63.6%)</span></div></div></div><div class="panel"><h2>최근 활동</h2><div class="activity-list"><div class="activity"><span class="activity-icon">✦</span><div>카드 방탄소년단 #021이 공개되었습니다.<small>관리자 · 20분 전</small></div></div><div class="activity"><span class="activity-icon">⌁</span><div>드롭 ‘드림스타 세트 A’가 생성되었습니다.<small>관리자 · 1시간 전</small></div></div><div class="activity"><span class="activity-icon">▦</span><div>새 카드 500개가 발급되었습니다.<small>전국 · 2시간 전</small></div></div></div></div><div class="panel"><h2>운영 알림</h2><div class="notice">코드 배치의 잔여 수량을 확인하세요.<br/>발급 종료 전 새 드롭을 준비할 수 있습니다.</div></div></div>`;}
function cardsView(){return `<div class="toolbar"><input class="search" id="card-search" placeholder="카드명, 아티스트 검색" /><select class="filter" id="card-status"><option value="all">모든 상태</option><option value="published">공개됨</option><option value="draft">비공개</option></select><button class="primary" id="new-card">+ 카드 등록</button></div><div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>카드</th><th>아티스트 / 멤버</th><th>등급</th><th>발행 수량</th><th>상태</th><th>관리</th></tr></thead><tbody id="card-rows">${cardRows(state.cards)}</tbody></table></div></div>`;}
function cardRows(cards){return cards.map(card=>`<tr><td><div class="card-cell"><span class="thumb">✦</span>${escapeHtml(card.title)}</div></td><td>${escapeHtml(card.artist)}<br/><span class="eyebrow">${escapeHtml(card.member)}</span></td><td><strong>${escapeHtml(card.rarity)}</strong></td><td>${Number(card.supply).toLocaleString()}</td><td><span class="badge ${card.status==='draft'?'draft':''}">${card.status==='published'?'공개됨':'비공개'}</span></td><td>${card.status==='draft'?`<button class="secondary publish" data-id="${escapeHtml(card.id)}">공개하기</button>`:'<span class="eyebrow">게시 완료</span>'}</td></tr>`).join('');}
function batchesView(){return `<div class="batch-layout"><div class="panel"><h2>새 코드 배치 만들기</h2><form class="form" id="batch-form"><label class="field">드롭 선택<select name="dropId"><option value="demo-drop">드림스타 세트 A</option><option value="demo-drop-b">드림스타 세트 B</option></select></label><label class="field">생성 수량<input name="quantity" type="number" min="1" value="1000" required /><span class="hint">코드 1개당 한 번만 사용할 수 있습니다.</span></label><label class="field">코드 최대 사용 횟수<input name="maxUsesPerCode" type="number" min="1" value="1" required /></label><div class="code-preview">예시 코드　F9XQ-3M7A-1K8P</div><button class="primary" type="submit">코드 배치 생성</button></form></div><div class="panel"><h2>코드 발급 안내</h2><div class="notice">생성된 코드는 CSV로 내려받아 이벤트 현장 또는 공식 굿즈에 전달할 수 있습니다.<br/><br/>코드는 발급 후에도 사용량과 만료 상태를 확인할 수 있습니다.</div></div><div class="panel"><h2>최근 코드 배치</h2><div class="table-wrap"><table class="table"><thead><tr><th>배치</th><th>드롭</th><th>수량</th><th>상태</th></tr></thead><tbody><tr><td>F9XQ-••••</td><td>드림스타 세트 A</td><td>5,000</td><td><span class="badge">사용 중</span></td></tr><tr><td>8K2M-••••</td><td>드림스타 세트 B</td><td>3,000</td><td><span class="badge draft">예정</span></td></tr></tbody></table></div></div></div>`;}
function settingsView(){return `<div class="panel"><h2>운영 설정</h2><div class="form"><label class="field">관리자 이메일<input value="admin@fanfolio.com" /></label><label class="field">API 주소<input id="api-base" value="${escapeHtml(API_BASE)}" /><span class="hint">브라우저에서 관리자 API를 호출할 주소입니다.</span></label><button class="primary" id="save-settings">설정 저장</button></div></div>`;}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
async function api(path, options={}){const response=await fetch(`${API_BASE}${path}`,{...options,credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})}});if(!response.ok)throw new Error(`API ${response.status}`);return response.json();}
async function loadDashboard(){try{const result=await api('/admin/dashboard');state.metrics=result.data.metrics;layout()}catch{toast('백엔드 연결 전 데모 데이터를 표시합니다.')}}
function bind(){document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{state.view=button.dataset.view;layout();if(state.view==='dashboard')loadDashboard()}));document.querySelector('#refresh')?.addEventListener('click',()=>{if(state.view==='dashboard')loadDashboard();else{toast('화면을 새로고침했습니다.');layout()}});document.querySelector('#logout')?.addEventListener('click',()=>toast('관리자 로그아웃 API 연결 예정'));document.querySelector('#save-settings')?.addEventListener('click',()=>{localStorage.setItem('fanfolio_api_base',document.querySelector('#api-base').value);toast('설정을 저장했습니다.')});document.querySelector('#new-card')?.addEventListener('click',()=>toast('카드 등록 API 계약 준비 중입니다.'));document.querySelector('#card-search')?.addEventListener('input',(event)=>{const query=event.target.value.toLowerCase();document.querySelector('#card-rows').innerHTML=cardRows(state.cards.filter(card=>`${card.title}${card.artist}${card.member}`.toLowerCase().includes(query)))});document.querySelector('#card-status')?.addEventListener('change',(event)=>{const value=event.target.value;document.querySelector('#card-rows').innerHTML=cardRows(state.cards.filter(card=>value==='all'||card.status===value))});document.querySelectorAll('.publish').forEach(button=>button.addEventListener('click',async()=>{try{await api(`/admin/cards/${button.dataset.id}/publish`,{method:'POST',body:'{}'});const card=state.cards.find(item=>item.id===button.dataset.id);if(card)card.status='published';layout();toast('카드를 공개했습니다.')}catch{toast('카드 공개 API를 호출하지 못했습니다. 데모 카드에는 적용하지 않습니다.')}}));document.querySelector('#batch-form')?.addEventListener('submit',async(event)=>{event.preventDefault();const form=new FormData(event.target);try{const result=await api('/admin/redeem-code-batches',{method:'POST',body:JSON.stringify({dropId:form.get('dropId'),quantity:Number(form.get('quantity')),maxUsesPerCode:Number(form.get('maxUsesPerCode'))})});toast(`코드 배치를 생성했습니다: ${result.data.id}`)}catch{toast('백엔드 연결 전입니다. 코드 배치 입력을 확인했습니다.')}})}
layout();
