import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import test from 'node:test'

const appSource = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')
const fanHubSource = readFileSync(new URL('../src/components/FanSocialHub.tsx', import.meta.url), 'utf8')
const publicCollectionSource = readFileSync(new URL('../src/components/PublicCollection.tsx', import.meta.url), 'utf8')
const tradeComposerSource = readFileSync(new URL('../src/components/TradeComposer.tsx', import.meta.url), 'utf8')
const fanProfileUrl = new URL('../src/components/FanPublicProfile.tsx', import.meta.url)
const fanProfileSource = existsSync(fileURLToPath(fanProfileUrl)) ? readFileSync(fanProfileUrl, 'utf8') : ''

test('fan discovery opens a dedicated public fan profile before collection', () => {
  assert.match(fanHubSource, /onOpenProfile/)
  assert.match(fanHubSource, /onOpenCollection/)
  assert.match(fanHubSource, /같은 아티스트/)
  assert.match(fanHubSource, /거래 가능/)
  assert.match(fanHubSource, /찾는 카드 보유/)
  assert.match(fanHubSource, /추천 팬/)
  assert.match(fanHubSource, /총 \{filteredItems\.length\}명/)
  assert.match(fanHubSource, /fan-social-card-preview/)
  assert.match(appSource, /publicFanProfileIdFromPath/)
  assert.match(appSource, /<FanPublicProfile/)
  assert.match(fanProfileSource, /대표 컬렉션/)
  assert.match(fanProfileSource, /컬렉션 진행률/)
  assert.match(fanProfileSource, /교환 가능한 카드/)
  assert.match(fanProfileSource, /이 팬이 원하는 카드/)
  assert.match(fanProfileSource, /collection\.wantedCards/)
  assert.match(fanProfileSource, /팔로우 중인 아티스트/)
  assert.match(fanProfileSource, /팔로워/)
  assert.match(fanProfileSource, /공개 카드/)
  assert.match(fanHubSource, /<InlineIcon name="grid"/)
  assert.match(fanHubSource, /<InlineIcon name="rotate"/)
  assert.match(fanHubSource, /tabIndex=\{0\}/)
  assert.match(fanHubSource, /event\.target as HTMLElement\)\.closest\('button, a, input, select, textarea'\)/)
  assert.match(fanHubSource, /event\.key === 'Enter' \|\| event\.key === ' '/)
  assert.doesNotMatch(fanHubSource, /[▣◇⌕‹]/)
})

test('fan discovery cards keep identity, affinity, stats, and card previews in separate responsive rows', () => {
  assert.match(fanHubSource, /className="fan-social-avatar-button"/)
  assert.match(fanHubSource, /className="fan-social-affinity"/)
  assert.match(fanHubSource, /className="fan-social-card-previews"/)
  const css = readFileSync(new URL('../src/fan-community-reference.css', import.meta.url), 'utf8')
  assert.match(css, /\.fan-social-card-preview \.fan-social-avatar-button\s*\{[^}]*grid-column:\s*1/s)
  assert.match(css, /\.fan-social-card-preview \.fan-social-affinity\s*\{[^}]*grid-column:\s*2 \/ 4/s)
  assert.match(css, /\.fan-social-card-preview \.fan-social-card-previews\s*\{[^}]*grid-column:\s*2 \/ 4/s)
})

test('follow controls expose one shared and visually distinct pressed state', () => {
  const css = readFileSync(new URL('../src/fan-community-reference.css', import.meta.url), 'utf8')

  assert.match(appSource, /className={`follow-state-button\$\{fan\.isFollowing \? ' following' : ''\}`}/)
  assert.match(appSource, /aria-pressed=\{fan\.isFollowing\}/)
  assert.match(appSource, /fan\.isFollowing && <InlineIcon name="check" \/>/)
  assert.match(fanProfileSource, /className={`follow-state-button\$\{following \? ' following' : ''\}`}/)
  assert.match(fanProfileSource, /aria-pressed=\{following\}/)
  assert.match(fanProfileSource, /following && <InlineIcon name="check" \/>/)
  assert.match(css, /\.follow-state-button\s*\{[^}]*background:\s*linear-gradient[^}]*color:\s*#fff/s)
  assert.match(css, /\.follow-state-button\.following\s*\{[^}]*background:\s*#f2efff[^}]*color:\s*#5e46d8/s)
  assert.match(css, /\.follow-state-button \.inline-icon\s*\{[^}]*width:\s*13px[^}]*height:\s*13px/s)
})

test('fan discovery artist chips stay left-aligned inside the identity column', () => {
  const css = readFileSync(new URL('../src/fan-community-reference.css', import.meta.url), 'utf8')
  assert.match(css, /\.fan-social-card-preview \.fan-social-copy > \.fan-social-tags\s*\{[^}]*grid-column:\s*1[^}]*justify-self:\s*start[^}]*width:\s*100%/s)
  assert.match(css, /\.fan-social-card-preview\s*\{[^}]*min-width:\s*0/s)
})

test('fan discovery identity copy keeps the full row beneath the compact follow button', () => {
  const css = readFileSync(new URL('../src/fan-community-reference.css', import.meta.url), 'utf8')
  assert.match(css, /\.fan-social-card-preview > \.fan-social-copy\s*\{[^}]*grid-column:\s*2 \/ 4[^}]*grid-row:\s*1 \/ span 2/s)
  assert.match(css, /\.fan-social-card-preview > \.fan-social-copy\s*\{[^}]*grid-template-rows:\s*30px auto/s)
  assert.match(css, /\.fan-social-card-preview > \.fan-social-copy > strong\s*\{[^}]*display:\s*flex[^}]*align-items:\s*center/s)
  assert.match(css, /\.fan-social-card-preview > \.fan-social-copy > \.fan-social-tags\s*\{[^}]*grid-column:\s*1 \/ -1[^}]*width:\s*100%/s)
})

test('fan discovery affinity copy uses the reference heart icon and leaves room for artist chips', () => {
  assert.match(fanHubSource, /<p className="fan-social-affinity"><InlineIcon name="heart" \/>/)
  const css = readFileSync(new URL('../src/fan-community-reference.css', import.meta.url), 'utf8')
  assert.match(css, /\.fan-social-card-preview > button:not\(\.fan-social-profile\)\s*\{[^}]*align-self:\s*start[^}]*width:\s*62px[^}]*height:\s*30px/s)
  assert.match(css, /\.fan-social-card-preview\s*\{[^}]*grid-template-columns:\s*64px minmax\(0, 1fr\) 62px/s)
  assert.match(css, /\.fan-social-affinity \.inline-icon\s*\{[^}]*width:\s*14px[^}]*height:\s*14px/s)
})

test('public collection supports discovery filters and a clear trade path', () => {
  assert.match(publicCollectionSource, /versionOptions/)
  assert.match(publicCollectionSource, /교환 가능/)
  assert.match(tradeComposerSource, /컬렉션 매칭/)
  assert.match(publicCollectionSource, /공개 컬렉션/)
  assert.match(publicCollectionSource, /교환 가능한 카드/)
  assert.match(publicCollectionSource, /collection\.nickname/)
  assert.match(publicCollectionSource, /collection\.summary\.ownedCount/)
  assert.match(publicCollectionSource, /tradableCards\.length/)
  assert.match(publicCollectionSource, /public-collection-slot missing/)
  assert.match(tradeComposerSource, /내가 보내는 카드/)
  assert.match(tradeComposerSource, /받고 싶은 카드/)
  assert.match(tradeComposerSource, /거래 조건 확인/)
  assert.match(tradeComposerSource, /서로 원하는 카드가 일치했어요/)
  assert.match(tradeComposerSource, /선택한 카드를 확인했어요/)
  assert.match(tradeComposerSource, /<InlineIcon name="puzzle"/)
  assert.match(tradeComposerSource, /<InlineIcon name="shield"/)
  assert.match(tradeComposerSource, /<InlineIcon name="lock"/)
  assert.match(fanProfileSource, /collection\.nickname/)
  assert.match(fanProfileSource, /collection\.summary\.followerCount/)
  assert.match(fanProfileSource, /collection\.summary\.ownedCount/)
  assert.doesNotMatch(tradeComposerSource, /[◆▣⬡]/)
})

test('public fan profile derives artist and pack display from backend collection data', () => {
  assert.doesNotMatch(fanProfileSource, /login\/dreamscape-group|card-pack-dreamscape-generated/)
  assert.doesNotMatch(fanProfileSource, /정규 1집 · DREAMSCAPE|DREAMSCAPE/)
  assert.match(fanProfileSource, /const representativeCard = cards\.find\(card => card\.artistId \|\| card\.artistName \|\| card\.seasonName\) \?\? cards\[0\]/)
  assert.match(fanProfileSource, /const primaryArtistName = representativeCard\?\.artistName \?\? '아티스트'/)
  assert.match(fanProfileSource, /const primaryPackLabel = representativeCard\?\.seasonName \?\? representativeCard\?\.name \?\? '컬렉션'/)
  assert.match(fanProfileSource, /const representativeImage = resolveApiUrl\(representativeCard\?\.imageUrl\) \|\| avatarFallback/)
  assert.match(fanProfileSource, /const primaryPackCount = representativeCard/)
  assert.doesNotMatch(fanProfileSource, /ownedCount \/ 40|ownedCount\}\/40/)
})

test('public fan profile starts trade from the selected tradable-card list', () => {
  assert.match(fanProfileSource, /disabled=\{tradableCards\.length === 0\} onClick=\{\(\) => onTrade\(\)\}>거래 제안/)
  assert.match(appSource, /\/trades\/new\?recipient=\$\{encodeURIComponent\(publicFanProfileUserId\)\}/)
  assert.doesNotMatch(appSource, /onTrade=.*\/fans\/\$\{encodeURIComponent\(publicFanProfileUserId\)\}\/collection\?filter=tradable/)
  assert.match(fanProfileSource, /followFan\(userId\)/)
  assert.match(fanProfileSource, /unfollowFan\(userId\)/)
})

test('public collection derives owner badge and featured pack from backend collection cards', () => {
  assert.doesNotMatch(publicCollectionSource, /card-pack-dreamscape-generated/)
  assert.doesNotMatch(publicCollectionSource, /드림스케이프|정규 1집 · DREAMSCAPE/)
  assert.match(publicCollectionSource, /const representativeCard = collection\.cards\.find\(card => card\.seasonName \|\| card\.artistName \|\| card\.name\) \?\? collection\.cards\[0\]/)
  assert.match(publicCollectionSource, /const ownerBadgeLabel = representativeCard\?\.artistName \?\? representativeCard\?\.seasonName \?\? '공개 컬렉션'/)
  assert.match(publicCollectionSource, /const featuredPackLabel = representativeCard\?\.seasonName \?\? representativeCard\?\.name \?\? '카드팩 보기'/)
  assert.match(publicCollectionSource, /const featuredPackImage = resolveApiUrl\(representativeCard\?\.imageUrl\) \|\| ''/)
  assert.match(publicCollectionSource, /map\(card => card\.seasonName\)/)
  assert.doesNotMatch(publicCollectionSource, /Math\.max\(40, collection\.summary\.ownedCount\)/)
})

test('discover preview follows the selected recommendation dashboard layout', () => {
  assert.match(appSource, /아티스트, 카드팩, 팬을 검색해보세요/)
  assert.match(appSource, /추천 팬/)
  assert.match(appSource, /공개 컬렉션/)
  assert.match(appSource, /새 카드팩/)
  assert.match(appSource, /진행 중인 이벤트/)
})

test('development previews expose every fan community screen independently', () => {
  for (const preview of ['fan-social', 'fan-profile', 'public-collection', 'trade-composer', 'discover-event']) {
    assert.match(appSource, new RegExp(`preview === '${preview}'`))
  }
})

test('authenticated fan community routes use backend data instead of preview injections', () => {
  assert.doesNotMatch(appSource, /isLocalFanAppRoute/)
  assert.doesNotMatch(appSource, /function LocalFanApp\(/)
  assert.doesNotMatch(appSource, /import\.meta\.env\.DEV && !signedIn && isLocalFanAppRoute\(pathname\)/)
  assert.match(appSource, /pathname === '\/fans'/)
  assert.match(appSource, /\/fans\/\$\{encodeURIComponent\(userId\)\}/)
  assert.match(appSource, /\/fans\/\$\{encodeURIComponent\(userId\)\}\/collection/)
  assert.match(appSource, /\/trades\/new\?recipient=/)
  assert.match(fanHubSource, /searchFans\(submittedQuery\)/)
  assert.match(tradeComposerSource, /getPublicCollection\(recipientUserId\)/)
  assert.match(tradeComposerSource, /requestedUserCardIds\.includes\(card\.userCardId\)/)
  assert.doesNotMatch(tradeComposerSource, /const wanted = cards\[1\]/)
})

test('fan community previews share the primary shell gutter and preserve compact spacing', () => {
  const css = readFileSync(new URL('../src/fan-community-reference.css', import.meta.url), 'utf8')
  assert.doesNotMatch(css, /main\.discover-shell\s*\{[^}]*padding-inline:\s*0/s)
  assert.doesNotMatch(css, /main\.app-shell\.discover-shell > header\.app-header\s*\{[^}]*width:\s*calc\(100% - 32px\)/s)
  assert.match(css, /main\.discover-shell \.discover-hub\s*\{[^}]*padding:\s*0 0 110px/s)
  assert.match(css, /main\.fan-social-shell\s*\{[^}]*padding-inline:\s*0/s)
  assert.match(css, /\.fan-social-content\s*\{[^}]*padding:\s*12px 16px 44px/s)
  assert.match(css, /\.fan-social-tags \.inline-icon\s*\{[^}]*width:\s*12px/s)
  assert.match(css, /\.discover-collection-ownerline/)
  assert.match(css, /\.discover-fan-list article > \.discover-fan-profile\s*\{[^}]*height:\s*auto/s)
  assert.match(css, /@keyframes trade-card-float/)
  assert.match(css, /prefers-reduced-motion:\s*reduce/)
})

test('fan community visuals keep icons, avatars, chips, and motion aligned with the reference', () => {
  const css = readFileSync(new URL('../src/fan-community-reference.css', import.meta.url), 'utf8')

  assert.match(fanProfileSource, /<InlineIcon name="rotate"/)
  assert.match(fanProfileSource, /<InlineIcon name="grid"/)
  assert.doesNotMatch(fanProfileSource, /[⇆▣⟳]/)

  assert.equal((tradeComposerSource.match(/className="trade-card-visual"/g) ?? []).length, 2)
  assert.match(css, /\.discover-fan-list \.profile-avatar\s*\{[^}]*border-radius:\s*50%/s)
  assert.match(css, /main\.discover-shell \.discover-featured-section \.section-heading button\s*\{[^}]*color:\s*#654cdd[^}]*font-weight:\s*800/s)
  assert.match(css, /\.fan-social-tags i\s*\{[^}]*display:\s*inline-flex[^}]*width:\s*auto/s)
  assert.match(css, /\.fan-profile-panel \.section-heading\s*\{[^}]*margin:\s*0 0 12px/s)
  assert.match(css, /\.fan-profile-tradable-cards \.more \.inline-icon\s*\{[^}]*width:\s*22px[^}]*height:\s*22px/s)
  assert.match(css, /\.fan-profile-wanted-cards\s*\{[^}]*grid-template-columns:\s*repeat\(3/s)
  assert.match(css, /\.fan-profile-wanted-panel \.section-heading > strong/)
  assert.match(fanProfileSource, /거래 제안 준비/)
  assert.match(css, /\.fan-profile-trade-ready\s*\{[^}]*grid-template-columns:/s)
  assert.match(css, /\.fan-profile-trade-ready > span\s*\{[^}]*border-radius:\s*50%/s)
  assert.match(css, /\.fan-profile-summary > div > span\s*\{[^}]*width:\s*42px[^}]*border-radius:\s*50%[^}]*background:\s*#f1eeff/s)
  assert.match(css, /\.fan-profile-summary > div > span \.inline-icon\s*\{[^}]*width:\s*22px[^}]*height:\s*22px/s)
  assert.match(css, /\.trade-match-cards > article \.trade-card-visual\s*\{[^}]*animation:\s*trade-card-float/s)
  assert.doesNotMatch(css, /\.trade-match-cards > article\s*\{[^}]*animation:\s*trade-card-float/s)
})

test('secondary fan-community controls have real destinations or state changes', () => {
  assert.match(fanProfileSource, /onOpenArtist/)
  assert.match(fanProfileSource, /onClick=\{\(\) => onOpenArtist/)
  assert.match(publicCollectionSource, /onOpenPackCatalog/)
  assert.match(publicCollectionSource, /featuredPackId/)
  assert.match(publicCollectionSource, /public-collection-season[^>]*onClick=\{\(\) => onOpenPackCatalog\(collection\.featuredPackId \?\? undefined\)\}/)
  assert.match(tradeComposerSource, /selectedOfferedUserCardId/)
  assert.match(tradeComposerSource, /selectNextOfferedCard/)
  assert.match(tradeComposerSource, /onClick=\{selectNextOfferedCard\}/)
  assert.doesNotMatch(tradeComposerSource, /<button type="button">다른 카드로 변경/)
  assert.match(appSource, /onOpenArtist=\{artistId => navigateAppPath/)
  assert.match(appSource, /const openPublicPackCatalog = \(packId\?: string\) =>/)
  assert.match(appSource, /onOpenPackCatalog=\{openPublicPackCatalog\}/)
  assert.match(appSource, /\/discover\/packs\/\$\{encodeURIComponent\(packId\)\}/)
})

test('live fan discovery renders backend metadata and applies each filter', () => {
  assert.match(fanHubSource, /favoriteArtists/)
  assert.match(fanHubSource, /tradableCount/)
  assert.match(fanHubSource, /matchingWishlistCount/)
  assert.match(fanHubSource, /latestCardAt/)
  assert.match(fanHubSource, /previewCards/)
  assert.match(fanHubSource, /filteredItems/)
  assert.match(fanHubSource, /onOpenTrades\(fan\.id\)/)
  assert.doesNotMatch(fanHubSource, /const fanMeta =/)
  assert.doesNotMatch(fanHubSource, /const previewCards =/)
})

test('trade composer submits the displayed requested card once', () => {
  assert.match(tradeComposerSource, /effectiveRequestedUserCardIds/)
  assert.match(tradeComposerSource, /requestedUserCardIds:\s*effectiveRequestedUserCardIds/)
  assert.match(tradeComposerSource, /submitting/)
  assert.match(tradeComposerSource, /if \(!mine \|\| !wanted \|\| !confirmed \|\| submitting\) return/)
  assert.match(tradeComposerSource, /disabled=\{!confirmed \|\| submitting\}/)
})

test('trade proposal starts with a four-column card picker and continues to confirmation', () => {
  assert.match(tradeComposerSource, /function TradeCardPicker/)
  assert.match(tradeComposerSource, /상대가 원하는 카드/)
  assert.match(tradeComposerSource, /내가 보낼 카드/)
  assert.match(appSource, /tradeStep !== 'confirm'/)
  assert.match(appSource, /initialOfferedUserCardId=/)
})

test('fan-community routes preserve a validated return destination', () => {
  assert.match(appSource, /safeAppReturnPath/)
  assert.match(appSource, /routeWithReturnTo/)
  assert.match(appSource, /returnTo/)
  assert.match(appSource, /window\.history\.replaceState\(\{\}, '', '\/fans'\)/)
})

test('collection exposes the live wishlist registration flow', () => {
  const css = readFileSync(new URL('../src/reference.css', import.meta.url), 'utf8')
  assert.match(appSource, /showWishlistPicker/)
  assert.match(appSource, /\/collection\/wishlist/)
  assert.match(appSource, /function WishlistPicker/)
  assert.match(appSource, /preview === 'wishlist-picker'/)
  assert.match(appSource, /persist=\{false\}/)
  assert.match(appSource, /saveWishlistCard\(cardId\)/)
  assert.match(appSource, /removeWishlistCard\(cardId\)/)
  assert.match(appSource, /원하는 카드 등록/)
  assert.match(appSource, /카드명 또는 멤버를 검색해보세요/)
  assert.match(appSource, /원하는 카드로 등록/)
  assert.match(css, /main\.collection-shell \.collection-wishlist-entry/)
  assert.match(css, /main\.wishlist-picker-shell \.wishlist-picker-grid/)
})
