import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const appSource = await readFile(new URL('../src/App.tsx', import.meta.url), 'utf8')
const appCssSource = await readFile(new URL('../src/App.css', import.meta.url), 'utf8')
const referenceCssSource = await readFile(new URL('../src/reference.css', import.meta.url), 'utf8')
const cardVisualSource = await readFile(new URL('../src/utils/cardVisual.ts', import.meta.url), 'utf8')
const interactiveCardSource = await readFile(new URL('../src/components/InteractiveCollectibleCard.tsx', import.meta.url), 'utf8')

test('home foregrounds the signed-in fan collection and keeps its primary actions working', () => {
  assert.match(appSource, /`member:\$\{card\.memberName/)
  assert.match(appSource, /nickname=\{currentUser\?\.nickname/)
  assert.match(appSource, /새 카드가 도착했어요/)
  assert.match(appSource, /className="collection-spotlight"/)
  assert.match(appSource, /role="progressbar"/)
  assert.match(appSource, /Math\.min\(100, Math\.max\(0, summary\.completionRate\)\)/)
  assert.doesNotMatch(appSource, />UR <i>·<\/i> OFFICIAL</)
  assert.match(appSource, /최근 수집/)
  assert.match(appSource, /className="collection-register-cta"/)
  assert.match(appSource, /<RedeemIcon name="scan"/)
  assert.match(appSource, /onClick=\{onRedeem\}/)
  assert.match(appSource, /onClick=\{\(\) => onSelect\(featured\)\}/)
  assert.match(appSource, /onClick=\{onCollection\}/)
})

test('legacy demo cards use a member-matched first-party portrait', () => {
  assert.match(cardVisualSource, /seed\.includes\('유나'\)/)
  assert.match(cardVisualSource, /return cardYuna/)
  assert.match(cardVisualSource, /seed\.includes\('민호'\)/)
  assert.match(cardVisualSource, /return cardMinho/)
})

test('fan navigation uses five persistent destinations with alerts retained in the header', () => {
  assert.equal([...appSource.matchAll(/<NavItem /g)].length, 5)
  assert.match(appSource, /label="홈"/)
  assert.match(appSource, /label="탐색"/)
  assert.match(appSource, /label="보관함"/)
  assert.match(appSource, /label="팬 레벨"/)
  assert.match(appSource, /label="상점"/)
  assert.match(appSource, /label="탐색"[\s\S]*label="보관함"[\s\S]*label="홈"/)
  assert.match(appSource, /header-alert-button/)
  assert.match(appSource, /navigateTab\('alerts'\)/)
})

test('top header and bottom nav share one geometry across all app tabs', () => {
  assert.match(appCssSource, /\.app-shell\{[\s\S]*padding:18px 22px 118px/)
  assert.match(appCssSource, /\.app-header\{[\s\S]*min-height:58px/)
  assert.match(appCssSource, /\.app-header h1\{[\s\S]*font-size:28px/)
  assert.match(appCssSource, /\.bottom-nav\{[\s\S]*display:grid/)
  assert.match(appCssSource, /\.bottom-nav\{[\s\S]*grid-template-columns:repeat\(5,1fr\)/)
  assert.doesNotMatch(appCssSource, /\.home-shell \.app-header/)
  assert.doesNotMatch(appCssSource, /\.home-shell \.bottom-nav/)
})

test('collection spotlight styles create the selected editorial hierarchy and mobile rail', () => {
  assert.match(appCssSource, /\.collection-spotlight\{/)
  assert.match(appCssSource, /\.collection-spotlight::after/)
  assert.match(appCssSource, /\.collection-progress-track/)
  assert.match(appCssSource, /\.recent-collection-row/)
  assert.match(appCssSource, /overflow-x:auto/)
  assert.match(appCssSource, /\.collection-register-cta/)
  assert.match(appCssSource, /@media\(max-width:360px\)/)
})

test('collection landing keeps recent cards concise and opens the dedicated card repository', () => {
  assert.match(appSource, /className="collection-reference"/)
  assert.match(appSource, /className="collection-progress-card"/)
  assert.match(appSource, /className="app-header-description"/)
  assert.match(appSource, /className="collection-recent-grid"/)
  assert.match(appSource, /컬렉션 진행률/)
  assert.match(appSource, /onClick=\{onCards\}>전체 보기/)
  assert.doesNotMatch(appSource, /className="collection-filter-trigger"/)
  assert.doesNotMatch(appSource, /className="collection-manage-card"/)
  assert.doesNotMatch(appSource, /className="collection-summary-grid"/)
  assert.match(appSource, /const sourceCards = collectionDataReady \? collectionCards : import\.meta\.env\.DEV \? fallbackCollectionCards : \[\]/)
  assert.match(appSource, /const recentCards = sourceCards\.slice\(0, 4\)/)
  assert.match(referenceCssSource, /Collection reference contract[\s\S]*?\.collection-recent-grid[\s\S]*?grid-template-columns:\s*repeat\(4/)
  assert.match(referenceCssSource, /main\.collection-shell \.collection-reference-card img \{[^}]*height:calc\(100% - 24px\)!important;/)
  assert.doesNotMatch(referenceCssSource, /main\.collection-shell \.collection-reference-card img \{[^}]*height:(?:112|106)px!important;/)
  assert.match(referenceCssSource, /main\.collection-shell \.app-header \{ min-height:0!important; margin-bottom:0!important; \}/)
})

test('collection recent card badges preserve the rarity returned by the collection API', () => {
  assert.match(appSource, /const rarity = card\.rarity \?\? \(index === 0 \? 'UR' : index < 3 \? 'SR' : index === 3 \? 'R' : 'N'\)/)
})

test('card collection repository supports admin-named groups, version packs, and a four-column catalog', () => {
  assert.match(appSource, /window\.location\.pathname === '\/collection\/cards'/)
  assert.match(appSource, /preview === 'card-collection'/)
  assert.match(appSource, /function CardCollectionRepository\(/)
  assert.match(appSource, /정규 1집 · DREAMSCAPE/)
  assert.match(appSource, /Nebula Ver\./)
  assert.match(appSource, /Starlight Ver\./)
  assert.match(appSource, /Midnight Ver\./)
  assert.match(appSource, /className="card-collection-pack-rail"/)
  assert.match(appSource, /className="card-collection-grid"/)
  assert.match(appSource, /aria-label="카드 정렬"/)
  assert.match(appSource, /aria-label="카드 필터"/)
  assert.match(referenceCssSource, /\.card-collection-grid\s*\{[^}]*grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/s)
  assert.match(referenceCssSource, /\.card-collection-slot\.missing/)
  assert.match(appSource, /if \(pathname === '\/collection\/cards'\) return 'collection'/)
})

test('card collection copy badges remain readable for large quantities', () => {
  assert.match(appSource, /function formatCardCopies\(copies: number\)/)
  assert.match(appSource, /copies > 99 \? '99\+' : String\(Math\.max\(0, copies\)\)/)
  assert.match(appSource, /copies: acquired \? \[1, 1, 12, 1, 1, 128/)
  assert.match(appSource, /<em aria-label=\{`\$\{slot\.copies\}장 보유`\}>\{formatCardCopies\(slot\.copies\)\}<\/em>/)
  assert.match(referenceCssSource, /\.card-collection-slot > em \{[^}]*width:auto;[^}]*min-width:20px;[^}]*padding:0 5px;[^}]*white-space:nowrap;/s)
})

test('owned collection cards open a dedicated detail screen with collection context', () => {
  assert.match(appSource, /type CardCollectionDetailItem =/)
  assert.match(appSource, /function CardCollectionDetail\(/)
  assert.match(appSource, /if \(selectedItem\) return <CardCollectionDetail/)
  assert.match(appSource, /groupName:\s*group\.displayName/)
  assert.match(appSource, /packName:\s*sourcePack\.name/)
  assert.match(appSource, /copies:\s*slot\.copies/)
  assert.match(appSource, /<strong>\{memberName\} · \{cardName\}<\/strong>/)
  assert.match(appSource, /<dt>컬렉션<\/dt><dd>\{item\.groupName\}<\/dd>/)
  assert.doesNotMatch(appSource, /card-collection-detail[\s\S]{0,1200}현재 적용 중/)
})

test('collection card detail flips by horizontal swipe and hides manual effect controls', () => {
  assert.match(appSource, /swipeToFlip/)
  assert.match(appSource, /showControls=\{false\}/)
  assert.match(appSource, /카드를 좌우로 밀어 뒷면을 확인해 보세요/)
  assert.match(interactiveCardSource, /Math\.abs\(deltaX\) >= 42/)
  assert.match(interactiveCardSource, /setVisibleSide\(current => current === 'front' \? 'back' : 'front'\)/)
  assert.match(interactiveCardSource, /showControls = true/)
  assert.match(interactiveCardSource, /\{showControls && presentation === 'detail'/)
})

test('both collectible card faces respond to pointer and device motion', () => {
  assert.match(interactiveCardSource, /const canTilt = visibleSide === 'back' \|\| effects\.front\.interaction !== 'static'/)
  assert.match(interactiveCardSource, /if \(canTilt\) \{[\s\S]*?--tilt-x[\s\S]*?--tilt-y/)
  assert.match(interactiveCardSource, /if \(visibleSide === 'front'\) \{[\s\S]*?--light-x[\s\S]*?--light-y/)
  assert.match(interactiveCardSource, /if \(!deviceMotionEnabled \|\| reducedEffects \|\| !supportsDeviceMotion\(\)\) return/)
  assert.doesNotMatch(interactiveCardSource, /visibleSide !== 'front' \|\| reducedEffects/)
  assert.match(appCssSource, /\.fan-card-collectible\.back\{[^}]*transform:perspective\(900px\) rotateX\(var\(--tilt-x\)\) rotateY\(var\(--tilt-y\)\)/)
})

test('collection detail renders the data supplied by an owned card', () => {
  assert.match(appSource, /apiFetch<\{ ok: true, data: UserCardDetail \}>\(`\/me\/cards\/\$\{item\.card\.userCardId\}`\)/)
  assert.match(appSource, /<h2>아티스트 메시지<\/h2>/)
  assert.match(appSource, /detail\?\.card\.signatureText \?\? item\.artistMessage/)
  assert.match(appSource, /<dt>획득일<\/dt>/)
  assert.match(appSource, /<dt>카드 유형<\/dt>/)
  assert.match(appSource, /<dt>획득 경로<\/dt>/)
  assert.match(appSource, /detail\?\.card\.handwritingImageUrl/)
  assert.match(appSource, /detail\?\.card\.hasVoice && detail\.card\.voiceAudioUrl/)
  assert.match(appSource, /detail\?\.card\.hasVideo && detail\.card\.videoUrl/)
  assert.match(appSource, /card-collection-swipe-hint[\s\S]*?card-collection-detail-message[\s\S]*?card-collection-detail-info/)
})

test('collection inventory thumbnails stay inside their assigned grid track', () => {
  assert.match(referenceCssSource, /\.collection-reward-thumbnails img \{[^}]*width:42px!important;[^}]*height:42px!important;/)
  assert.match(referenceCssSource, /\.collection-reward-thumbnails img:nth-child\(4\) \{[^}]*left:42px!important;/)
  assert.match(referenceCssSource, /@media\(max-width:360px\)[\s\S]*?\.collection-reward-thumbnails img \{[^}]*width:38px!important;[^}]*height:38px!important;/)
  assert.match(referenceCssSource, /@media\(max-width:360px\)[\s\S]*?\.collection-reward-thumbnails img:nth-child\(4\) \{[^}]*left:33px!important;/)
})

test('home surfaces the editorial artist, new cards, and upcoming drop sections', () => {
  assert.match(appSource, /className="home-artist-section"/)
  assert.match(appSource, /관심 아티스트/)
  assert.match(appSource, /className="home-new-cards"/)
  assert.match(appSource, /새로 공개된 카드/)
  assert.match(appSource, /className="home-active-event"/)
  assert.match(appSource, /eventHome \? eventHome\.newCards\.map\(toCatalogCard\) : import\.meta\.env\.DEV \? fallbackHomeCards : \[\]/)
  assert.match(appSource, /eventHome \? eventHome\.featuredEvent : import\.meta\.env\.DEV \? fallbackHomeEvent : null/)
  assert.match(appSource, /eventHome \? eventHome\.upcomingEvents\[0\] \?\? eventHome\.featuredEvent : import\.meta\.env\.DEV \? fallbackHomeEvent : null/)
  assert.match(appSource, /activeEvent\.id\.startsWith\('demo-'\) \? onEvents\(\) : onEvent\(activeEvent\)/)
})

test('home markup follows the approved full-bleed editorial reference', () => {
  assert.match(appSource, /좋아하는 아티스트의<br \/><em>새로운 순간<\/em>/)
  assert.match(appSource, /className="home-event-spotlight-copy"/)
  assert.match(appSource, /className="home-event-dots"/)
  assert.match(appSource, /function FavoriteControl\(/)
  assert.match(appSource, /<FavoriteControl className="home-favorite-button"/)
  assert.match(appSource, /className="home-artist-backdrop"/)
  assert.match(appSource, /className="home-artist-badge"/)
  assert.match(appSource, /home-new-card-rarity rarity-\$\{rarity\.toLowerCase\(\)\}/)
  assert.match(appSource, /const \[newCardFavorites, setNewCardFavorites\] = useState<Set<string>>/)
  assert.match(appSource, /<FavoriteControl[\s\S]*className="home-new-card-favorite"/)
  assert.match(appSource, /aria-pressed=\{active\}/)
  assert.match(appSource, /toggleNewCardFavorite\(card\.id\)/)
  assert.match(appSource, /className="home-active-event-status"/)
  assert.match(appSource, /className="home-active-event-section"/)
  assert.match(appSource, />진행 중인 이벤트</)
  assert.match(appSource, /activeEvent\.endsAt \? `D-\$\{Math\.max\(0, Math\.ceil\(\(new Date\(activeEvent\.endsAt\)\.getTime\(\) - Date\.now\(\)\) \/ 86400000\)\)\}` : '자세히'/)
  assert.match(appSource, /const \[artistFavorites, setArtistFavorites\] = useState<Set<string>>/)
  assert.match(appSource, /home-artist-primary\$\{activeHomeArtistId === artist\.id/)
  assert.match(appSource, /<FavoriteControl[\s\S]*className="home-artist-favorite"/)
  assert.match(appSource, /const isFavorite = artistFavorites\.has\(artist\.id\)/)
  assert.match(appSource, /setArtistFavorites\(current => {/)
  assert.match(appSource, /className="home-artist-verified"/)
  assert.match(appSource, /function VerifiedIcon\(\)/)
})

test('home reference CSS uses the approved mobile density and lighter editorial weights', () => {
  assert.match(referenceCssSource, /--fan-shell:\s*430px/)
  assert.match(referenceCssSource, /\.home-page-title[\s\S]*font-size:\s*23px[\s\S]*font-weight:\s*700/)
  assert.match(referenceCssSource, /\.home-event-spotlight > button[\s\S]*height:\s*218px/)
  assert.match(referenceCssSource, /\.home-event-spotlight[\s\S]*margin:\s*0 0 14px/)
  assert.match(referenceCssSource, /\.home-shell \.header-profile-button[\s\S]*width:\s*32px[\s\S]*height:\s*32px/)
  assert.match(referenceCssSource, /\.home-artist-card[\s\S]*height:\s*132px/)
  assert.match(referenceCssSource, /\.home-shell \.app-header\s*\{\s*margin-bottom:\s*0/)
  assert.match(referenceCssSource, /\.home-artist-copy > b[\s\S]*font-size:\s*16px/)
  assert.match(referenceCssSource, /\.home-artist-members img[\s\S]*width:\s*30px[\s\S]*height:\s*30px/)
  assert.match(referenceCssSource, /\.home-favorite-button[\s\S]*width:\s*28px[\s\S]*height:\s*28px/)
  assert.match(referenceCssSource, /\.home-artist-favorite[\s\S]*width:\s*28px[\s\S]*height:\s*28px/)
  assert.match(referenceCssSource, /\.home-artist-favorite\.is-active[\s\S]*fill:\s*#fff/)
  assert.match(referenceCssSource, /\.rarity-ur[\s\S]*background:\s*#6b43ea/)
  assert.match(referenceCssSource, /\.rarity-sr[\s\S]*background:\s*#1769e8/)
  assert.match(referenceCssSource, /\.home-new-cards\s*\{\s*margin-top:\s*8px/)
  assert.match(referenceCssSource, /\.home-new-card[\s\S]*aspect-ratio:\s*3\s*\/\s*4/)
  assert.match(referenceCssSource, /\.home-new-card-favorite[\s\S]*width:\s*20px[\s\S]*height:\s*20px/)
  assert.match(referenceCssSource, /\.home-active-event-section\s*\{\s*margin-top:\s*10px/)
  assert.match(referenceCssSource, /\.home-active-event > img[\s\S]*width:\s*84px[\s\S]*height:\s*60px/)
})

test('home hero is a real API-backed carousel with navigable editorial banners', () => {
  assert.match(appSource, /fanWeekNightStage/)
  assert.match(appSource, /fanWeekLavenderMeet/)
  assert.match(appSource, /aria-roledescription="carousel"/)
  assert.match(appSource, /className="home-event-track"/)
  assert.match(appSource, /const apiHeroEvents = eventHome/)
  assert.match(appSource, /const heroEvents = homeVisibleEvents/)
  assert.match(appSource, /onClick=\{event => \{[\s\S]*event\.stopPropagation\(\)[\s\S]*openHeroEvent\(slide\)/)
  assert.doesNotMatch(appSource, /fallbackHeroSlides.slice(1)/)
  assert.match(appSource, /draggable=\{false\}/)
  assert.match(appSource, /window\.setInterval/)
  assert.match(appSource, /home-event-dot active/)
  assert.match(referenceCssSource, /\.home-event-track[\s\S]*translate3d/)
  assert.match(referenceCssSource, /touch-action:\s*pan-y/)
})

test('reference entry routes and artist hub heading stay aligned with the approved fan flow', () => {
  assert.match(appSource, /if \(pathname === '\/' \|\| pathname === ''\) return 'home'/)
  assert.match(appSource, /heroUrl: dreamscapeHero/)
  assert.match(appSource, /resolveApiUrl\(event\.heroUrl\) \|\| dreamscapeHero/)
  assert.match(appSource, /const artistImage = artist\.imageUrl/)
  assert.doesNotMatch(appSource, /artist-hub-heading"><p className="eyebrow">ARTIST HUB<\/p><h2>탐색<\/h2>/)
})

test('horizontal home recommendations and collection pack rails hide browser scrollbars', () => {
  assert.match(appCssSource, /\.home-recommendation-row\{[^}]*scrollbar-width:none/s)
  assert.match(appCssSource, /\.home-recommendation-row::-webkit-scrollbar\{[^}]*display:none/s)
  assert.match(referenceCssSource, /\.card-collection-pack-rail > button:not\(\.card-collection-all-packs\)\{/)
  assert.match(referenceCssSource, /-webkit-line-clamp:2/)
})
