import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const appSource = await readFile(new URL('../src/App.tsx', import.meta.url), 'utf8')
const appCssSource = await readFile(new URL('../src/App.css', import.meta.url), 'utf8')
const referenceCssSource = await readFile(new URL('../src/reference.css', import.meta.url), 'utf8')
const cardVisualSource = await readFile(new URL('../src/utils/cardVisual.ts', import.meta.url), 'utf8')

test('home foregrounds the signed-in fan collection and keeps its primary actions working', () => {
  assert.match(appSource, /`member:\$\{card\.memberName/)
  assert.match(appSource, /nickname=\{currentUser\?\.nickname/)
  assert.match(appSource, /새 카드가 도착했어요/)
  assert.match(appSource, /className="collection-spotlight"/)
  assert.match(appSource, /role="progressbar"/)
  assert.match(appSource, /Math\.min\(100, Math\.max\(0, summary\.completionRate\)\)/)
  assert.doesNotMatch(appSource, />UR <i>·<\/i> OFFICIAL</)
  assert.match(appSource, /최근 수집/)
  assert.match(appSource, /className="collection-register-cta"/)
  assert.match(appSource, /<RedeemIcon name="scan"/)
  assert.match(appSource, /onClick=\{onRedeem\}/)
  assert.match(appSource, /onClick=\{\(\) => onSelect\(featured\)\}/)
  assert.match(appSource, /onClick=\{onCollection\}/)
})

test('legacy demo cards use a member-matched first-party portrait', () => {
  assert.match(cardVisualSource, /seed\.includes\('유나'\)/)
  assert.match(cardVisualSource, /return cardYuna/)
  assert.match(cardVisualSource, /seed\.includes\('민호'\)/)
  assert.match(cardVisualSource, /return cardMinho/)
})

test('fan navigation uses five persistent destinations with alerts retained in the header', () => {
  assert.equal([...appSource.matchAll(/<NavItem /g)].length, 5)
  assert.match(appSource, /label="홈"/)
  assert.match(appSource, /label="탐색"/)
  assert.match(appSource, /label="보관함"/)
  assert.match(appSource, /label="팬 레벨"/)
  assert.match(appSource, /label="마이"/)
  assert.match(appSource, /label="탐색"[\s\S]*label="보관함"[\s\S]*label="홈"/)
  assert.match(appSource, /header-alert-button/)
  assert.match(appSource, /navigateTab\('alerts'\)/)
})

test('top header and bottom nav share one geometry across all app tabs', () => {
  assert.match(appCssSource, /\.app-shell\{[\s\S]*padding:18px 22px 118px/)
  assert.match(appCssSource, /\.app-header\{[\s\S]*min-height:58px/)
  assert.match(appCssSource, /\.app-header h1\{[\s\S]*font-size:28px/)
  assert.match(appCssSource, /\.bottom-nav\{[\s\S]*display:grid/)
  assert.match(appCssSource, /\.bottom-nav\{[\s\S]*grid-template-columns:repeat\(5,1fr\)/)
  assert.doesNotMatch(appCssSource, /\.home-shell \.app-header/)
  assert.doesNotMatch(appCssSource, /\.home-shell \.bottom-nav/)
})

test('collection spotlight styles create the selected editorial hierarchy and mobile rail', () => {
  assert.match(appCssSource, /\.collection-spotlight\{/)
  assert.match(appCssSource, /\.collection-spotlight::after/)
  assert.match(appCssSource, /\.collection-progress-track/)
  assert.match(appCssSource, /\.recent-collection-row/)
  assert.match(appCssSource, /overflow-x:auto/)
  assert.match(appCssSource, /\.collection-register-cta/)
  assert.match(appCssSource, /@media\(max-width:360px\)/)
})

test('collection reference composition exposes progress, recent cards, management, and summary sections', () => {
  assert.match(appSource, /className="collection-reference"/)
  assert.match(appSource, /className="collection-progress-card"/)
  assert.match(appSource, /className="app-header-description"/)
  assert.match(appSource, /className="collection-recent-grid"/)
  assert.match(appSource, /className="collection-manage-card"/)
  assert.match(appSource, /className="collection-summary-grid"/)
  assert.match(appSource, /컬렉션 진행률/)
  assert.match(appSource, /카드 상세 관리/)
  assert.match(appSource, /총 카드/)
  assert.match(appSource, /완료 컬렉션/)
  assert.match(appSource, /진행 중/)
  assert.match(appSource, /희귀 카드/)
  assert.match(appSource, /dot: 'M12 3\.5a8\.5 8\.5/)
  assert.match(appSource, /onClick=\{\(\) => setShowAll\(true\)\}>전체 보기/)
  assert.match(appSource, /const sourceCards = collectionDataReady \? collectionCards : import\.meta\.env\.DEV \? fallbackCollectionCards : \[\]/)
  assert.match(referenceCssSource, /Collection reference contract[\s\S]*?\.collection-recent-grid[\s\S]*?grid-template-columns:\s*repeat\(4/)
  assert.match(referenceCssSource, /main\.collection-shell \.collection-reference-card img \{[^}]*height:calc\(100% - 24px\)!important;/)
  assert.doesNotMatch(referenceCssSource, /main\.collection-shell \.collection-reference-card img \{[^}]*height:(?:112|106)px!important;/)
  assert.match(referenceCssSource, /Collection reference contract[\s\S]*?\.collection-summary-grid[\s\S]*?grid-template-columns:\s*repeat\(4/)
  assert.match(referenceCssSource, /main\.collection-shell \.app-header \{ min-height:0!important; margin-bottom:0!important; \}/)
})

test('home surfaces the editorial artist, new cards, and upcoming drop sections', () => {
  assert.match(appSource, /className="home-artist-section"/)
  assert.match(appSource, /관심 아티스트/)
  assert.match(appSource, /className="home-new-cards"/)
  assert.match(appSource, /새로 공개된 카드/)
  assert.match(appSource, /className="home-active-event"/)
  assert.match(appSource, /eventHome \? eventHome\.newCards\.map\(toCatalogCard\) : import\.meta\.env\.DEV \? fallbackHomeCards : \[\]/)
  assert.match(appSource, /eventHome \? eventHome\.featuredEvent : import\.meta\.env\.DEV \? fallbackHomeEvent : null/)
  assert.match(appSource, /eventHome \? eventHome\.upcomingEvents\[0\] \?\? eventHome\.featuredEvent : import\.meta\.env\.DEV \? fallbackHomeEvent : null/)
  assert.match(appSource, /activeEvent\.id\.startsWith\('demo-'\) \? onEvents\(\) : onEvent\(activeEvent\)/)
})

test('home markup follows the approved full-bleed editorial reference', () => {
  assert.match(appSource, /좋아하는 아티스트의<br \/><em>새로운 순간<\/em>/)
  assert.match(appSource, /className="home-event-spotlight-copy"/)
  assert.match(appSource, /className="home-event-dots"/)
  assert.match(appSource, /function FavoriteControl\(/)
  assert.match(appSource, /<FavoriteControl className="home-favorite-button"/)
  assert.match(appSource, /className="home-artist-backdrop"/)
  assert.match(appSource, /className="home-artist-badge"/)
  assert.match(appSource, /home-new-card-rarity rarity-\$\{rarity\.toLowerCase\(\)\}/)
  assert.match(appSource, /const \[newCardFavorites, setNewCardFavorites\] = useState<Set<string>>/)
  assert.match(appSource, /<FavoriteControl[\s\S]*className="home-new-card-favorite"/)
  assert.match(appSource, /aria-pressed=\{active\}/)
  assert.match(appSource, /toggleNewCardFavorite\(card\.id\)/)
  assert.match(appSource, /className="home-active-event-status"/)
  assert.match(appSource, /className="home-active-event-section"/)
  assert.match(appSource, />진행 중인 이벤트</)
  assert.match(appSource, /activeEvent\.endsAt \? `D-\$\{Math\.max\(0, Math\.ceil\(\(new Date\(activeEvent\.endsAt\)\.getTime\(\) - Date\.now\(\)\) \/ 86400000\)\)\}` : '자세히'/)
  assert.match(appSource, /const \[artistFavorite, setArtistFavorite\] = useState\(false\)/)
  assert.match(appSource, /className="home-artist-primary"/)
  assert.match(appSource, /<FavoriteControl[\s\S]*className="home-artist-favorite"/)
  assert.match(appSource, /active=\{artistFavorite\}/)
  assert.match(appSource, /setArtistFavorite\(favorite => !favorite\)/)
  assert.match(appSource, /className="home-artist-verified"/)
  assert.match(appSource, /function VerifiedIcon\(\)/)
})

test('home reference CSS uses the approved mobile density and lighter editorial weights', () => {
  assert.match(referenceCssSource, /--fan-shell:\s*430px/)
  assert.match(referenceCssSource, /\.home-page-title[\s\S]*font-size:\s*23px[\s\S]*font-weight:\s*700/)
  assert.match(referenceCssSource, /\.home-event-spotlight > button[\s\S]*height:\s*218px/)
  assert.match(referenceCssSource, /\.home-event-spotlight[\s\S]*margin:\s*0 0 14px/)
  assert.match(referenceCssSource, /\.home-shell \.header-profile-button[\s\S]*width:\s*32px[\s\S]*height:\s*32px/)
  assert.match(referenceCssSource, /\.home-artist-card[\s\S]*height:\s*132px/)
  assert.match(referenceCssSource, /\.home-shell \.app-header\s*\{\s*margin-bottom:\s*0/)
  assert.match(referenceCssSource, /\.home-artist-copy > b[\s\S]*font-size:\s*16px/)
  assert.match(referenceCssSource, /\.home-artist-members img[\s\S]*width:\s*30px[\s\S]*height:\s*30px/)
  assert.match(referenceCssSource, /\.home-favorite-button[\s\S]*width:\s*28px[\s\S]*height:\s*28px/)
  assert.match(referenceCssSource, /\.home-artist-favorite[\s\S]*width:\s*28px[\s\S]*height:\s*28px/)
  assert.match(referenceCssSource, /\.home-artist-favorite\.is-active[\s\S]*fill:\s*#fff/)
  assert.match(referenceCssSource, /\.rarity-ur[\s\S]*background:\s*#6b43ea/)
  assert.match(referenceCssSource, /\.rarity-sr[\s\S]*background:\s*#1769e8/)
  assert.match(referenceCssSource, /\.home-new-cards\s*\{\s*margin-top:\s*8px/)
  assert.match(referenceCssSource, /\.home-new-card[\s\S]*aspect-ratio:\s*3\s*\/\s*4/)
  assert.match(referenceCssSource, /\.home-new-card-favorite[\s\S]*width:\s*20px[\s\S]*height:\s*20px/)
  assert.match(referenceCssSource, /\.home-active-event-section\s*\{\s*margin-top:\s*10px/)
  assert.match(referenceCssSource, /\.home-active-event > img[\s\S]*width:\s*84px[\s\S]*height:\s*60px/)
})

test('home hero is a real API-backed carousel with navigable editorial banners', () => {
  assert.match(appSource, /fanWeekNightStage/)
  assert.match(appSource, /fanWeekLavenderMeet/)
  assert.match(appSource, /aria-roledescription="carousel"/)
  assert.match(appSource, /className="home-event-track"/)
  assert.match(appSource, /const apiHeroEvents = eventHome/)
  assert.match(appSource, /const heroEvents = eventHome \? apiHeroEvents : featuredEvent \? \[featuredEvent\] : \[\]/)
  assert.match(appSource, /onClick=\{event => \{[\s\S]*event\.stopPropagation\(\)[\s\S]*openHeroEvent\(slide\)/)
  assert.doesNotMatch(appSource, /fallbackHeroSlides.slice(1)/)
  assert.match(appSource, /draggable=\{false\}/)
  assert.match(appSource, /window\.setInterval/)
  assert.match(appSource, /home-event-dot active/)
  assert.match(referenceCssSource, /\.home-event-track[\s\S]*translate3d/)
  assert.match(referenceCssSource, /touch-action:\s*pan-y/)
})

test('reference entry routes and artist hub heading stay aligned with the approved fan flow', () => {
  assert.match(appSource, /if \(pathname === '\/' \|\| pathname === ''\) return 'home'/)
  assert.match(appSource, /heroUrl: dreamscapeHero/)
  assert.match(appSource, /resolveApiUrl\(event\.heroUrl\) \|\| dreamscapeHero/)
  assert.match(appSource, /const artistImage = artist\?\.imageUrl/)
  assert.doesNotMatch(appSource, /artist-hub-heading"><p className="eyebrow">ARTIST HUB<\/p><h2>탐색<\/h2>/)
})
