const API_BASE = localStorage.getItem('fanfolio_api_base') || 'http://localhost:8000/api';
let SESSION_TOKEN = localStorage.getItem('fanfolio_session') || '';
const app = document.querySelector('#app');
const state = {
  authenticated: Boolean(SESSION_TOKEN), loginError: '', loginEmail: '', magicLinkRequested: false, step: 1, cardId: null, assetId: null,
  cardName: '', jobId: null, preview: null, previewImageSrc: '', signature: '', cards: [],
  form: { name: '드림 스페셜 카드 #5', memberId: 'member_yuna', seasonName: '2025 봄', templateId: 'template_signature_v1', rarity: 'R', signatureText: '항상 고마워요, 우리 함께해요!', hasVoice: true, issueLimit: 3000 },
};
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]));

function absoluteApiUrl(path) { if (!path) return ''; if (/^https?:\/\//.test(path)) return path; return `${API_BASE.replace(/\/api$/, '')}${path}`; }
function loginView() { const step = state.magicLinkRequested ? '<label class="field">로그인 토큰<input name="token" type="password" autocomplete="one-time-code" placeholder="이메일의 로그인 토큰" required /></label><button class="primary" type="submit">스튜디오 입장</button>' : '<label class="field">아티스트 이메일<input name="email" type="email" autocomplete="email" placeholder="artist@fanfolio.com" required /></label><button class="primary" type="submit">로그인 링크 받기</button>'; return `<main class="login-page"><div class="login-card"><p class="kicker">Fanfolio Artist Studio</p><div class="login-mark">✦</div><h1>아티스트 스튜디오 로그인</h1><p class="hint">아티스트 이메일로 받은 로그인 링크를 사용합니다.</p><form id="login-form" class="login-form">${step}</form>${state.loginError ? `<p class="login-error" role="alert">${esc(state.loginError)}</p>` : ''}</div></main>`; }

function shell(content) {
  app.innerHTML = `<div class="shell"><aside class="side"><div class="logo">Fanfolio <span>✦</span><small>아티스트 스튜디오</small></div><nav class="nav"><button class="active">⌂　스튜디오 홈</button><button>▦　카드 만들기</button><button>◇　내 카드</button><button>♡　팬 반응</button><button>⚙　설정</button></div><div class="profile"><span class="avatar">A</span><div><strong>아티스트</strong>ARTIST</div></aside><main class="workspace"><header class="top"><div><p class="kicker">Fanfolio Artist Studio</p><h1 class="title">${state.step === 1 ? '카드 만들기' : state.step === 2 ? '손글씨 추가' : state.step === 3 ? '카드 미리보기' : '검수 요청 완료'}</h1></div><div class="top-actions"><span class="save-state">● API 연결됨</span><button class="secondary" id="session-config">세션 설정</button><button class="secondary" id="logout">로그아웃</button></div></header>${content}</main></div><div class="toast" id="toast"></div>`;
  bindCommon();
}
function steps() { return `<div class="stepper"><div class="step ${state.step > 1 ? 'done' : 'current'}"><i>1</i> 기본 입력</div><div class="step-line"></div><div class="step ${state.step === 2 ? 'current' : state.step > 2 ? 'done' : ''}"><i>2</i> 손글씨</div><div class="step-line"></div><div class="step ${state.step === 3 ? 'current' : state.step > 3 ? 'done' : ''}"><i>3</i> 미리보기</div><div class="step-line"></div><div class="step ${state.step === 4 ? 'current' : ''}"><i>4</i> 검수·공개</div></div>`; }
function cardPreview(name = state.cardName || state.form.name, imageUrl = state.preview?.previewImageUrl) { const image = imageUrl ? `<img class="card-preview-image" src="${esc(absoluteApiUrl(imageUrl))}" alt="${esc(name)} 미리보기" />` : '<div class="card-figure"></div><div class="card-glow"></div>'; return `<div class="card-preview">${image}<div class="card-text"><strong>${esc(name || '새 특별 카드')}</strong><span>Fanfolio Special Card</span></div></div>`; }
function cardForm() {
  const f = state.form;
  return `${steps()}<div class="studio-grid"><div class="panel preview-panel"><h2>카드 미리보기</h2><div id="preview">${cardPreview()}</div><span class="hint">권장 이미지 1000×1500px · JPG/PNG</span></div><form class="panel form-panel" id="card-form"><h2>카드 정보</h2><label class="field">카드 이미지 *<input name="cardImage" type="file" accept="image/png,image/jpeg,image/webp" required /></label><label class="field">카드명 *<input name="name" placeholder="카드 이름을 입력하세요" required value="${esc(f.name)}" /></label><div class="row"><label class="field">그룹<select name="group"><option value="artist_nova3">드림스케이프</option></select></label><label class="field">멤버<select name="memberId"><option value="member_yuna" ${f.memberId === 'member_yuna' ? 'selected' : ''}>유나</option><option value="member_minho" ${f.memberId === 'member_minho' ? 'selected' : ''}>민호</option><option value="member_jei" ${f.memberId === 'member_jei' ? 'selected' : ''}>제이</option></select></label></div><div class="row"><label class="field">시즌<select name="seasonName"><option ${f.seasonName === '2025 봄' ? 'selected' : ''}>2025 봄</option><option ${f.seasonName === '2025 여름' ? 'selected' : ''}>2025 여름</option></select></label><label class="field">카드 타입<select name="templateId"><option value="template_signature_v1" ${f.templateId === 'template_signature_v1' ? 'selected' : ''}>스페셜</option><option value="template_basic_v1" ${f.templateId === 'template_basic_v1' ? 'selected' : ''}>일반</option></select></label></div><label class="field">희귀도<select name="rarity"><option value="R" ${f.rarity === 'R' ? 'selected' : ''}>R (레어)</option><option value="SR" ${f.rarity === 'SR' ? 'selected' : ''}>SR (슈퍼 레어)</option><option value="N" ${f.rarity === 'N' ? 'selected' : ''}>N (노멀)</option></select></label><label class="field">사인 메시지<textarea name="signatureText" maxlength="200" placeholder="팬에게 전하고 싶은 메시지를 입력하세요">${esc(f.signatureText)}</textarea><span class="hint">최대 200자 · 다음 단계에서 직접 손글씨를 추가할 수 있어요.</span></label><div class="toggle-row"><span>보이스 카드 <small class="hint">카드 수집 시 음성이 재생됩니다.</small></span><button type="button" class="toggle ${f.hasVoice ? 'on' : ''}" aria-label="보이스 카드 켜기" aria-pressed="${f.hasVoice}"></button></div><label class="field">발행 수량<input name="issueLimit" type="number" value="${esc(f.issueLimit)}" min="1" required /><span class="hint">발행 수량은 검수 전까지 수정할 수 있습니다.</span></label><div class="bottom-actions"><button type="button" class="secondary" id="save-draft">임시 저장</button><button class="primary" type="submit">다음: 손글씨</button></div></form></div>`;
}
function handwritingForm() { return `${steps()}<div class="handwriting-layout"><div class="panel"><h2>손글씨를 추가해 보세요</h2><p class="hint">직접 쓰거나 손글씨 이미지를 업로드하면 카드에 자연스럽게 합성됩니다.</p><div class="pad"><canvas id="signature-pad" width="760" height="420" aria-label="손글씨 입력 영역"></canvas><div class="pad-tools"><button class="secondary" id="clear-pad">지우기</button><span class="hint">손가락 또는 마우스로 작성</span></div></div><div style="height:12px"></div><label class="secondary" style="display:block;text-align:center">손글씨 이미지 업로드<input id="signature-file" type="file" accept="image/png,image/jpeg" hidden /></label><div style="height:12px"></div><button class="primary" id="remove-bg">배경 제거 요청</button><div id="job-area"></div></div><div class="panel"><h2>투명 손글씨 미리보기</h2><div class="handwriting-result" id="signature-result">${state.signature ? `<img src="${esc(state.signature)}" alt="입력한 손글씨 미리보기" />` : '<span class="hint">손글씨를 입력하면 여기에 표시됩니다.</span>'}</div><div style="height:15px"></div><div class="notice">배경 제거는 이미지 처리 작업으로 진행됩니다. 요청 후 결과가 준비되면 투명 PNG로 카드에 배치할 수 있습니다.</div><div class="bottom-actions" style="margin-top:18px"><button class="secondary" id="back-card">이전</button><button class="primary" id="next-review">다음: 미리보기</button></div></div></div>`; }
function review() { const metadata = state.preview?.metadata || {}; return `${steps()}<div class="review"><div class="panel preview-panel"><h2>검수 카드</h2>${cardPreview(metadata.name || state.cardName, state.previewImageSrc)}<span class="badge">특별 카드 · ${esc(metadata.rarity || state.form.rarity)}</span></div><div class="panel"><h2>공개 전 확인</h2><div class="checklist"><div class="check"><span>카드 정보 확인</span><span class="ok">확인 완료 ✓</span></div><div class="check"><span>이미지 및 메시지 확인</span><span class="ok">확인 완료 ✓</span></div><div class="check"><span>보이스 파일 확인</span><span class="ok">${metadata.hasVoice ? '확인 완료 ✓' : '사용 안 함'}</span></div><div class="check"><span>발행 수량 확인</span><span class="ok">${esc(metadata.issueLimit || state.form.issueLimit)}장</span></div></div><div style="height:18px"></div><label class="field"><span>검수 메모</span><textarea id="review-note" maxlength="500" placeholder="운영팀에 전달할 메모가 있나요?"></textarea></label><div class="notice" style="margin-top:15px">검수 요청 후 운영팀 확인을 거쳐 공개됩니다. 공개 전에는 언제든 임시 저장 카드에서 수정할 수 있습니다.</div><div class="bottom-actions" style="margin-top:18px"><button class="secondary" id="back-signature">이전</button><button class="primary" id="submit-review">검수 요청하기</button></div></div></div>`; }
function complete() { return `${steps()}<div class="panel complete"><div class="complete-icon">✓</div><h2>검수 요청을 보냈어요</h2><p class="hint">운영팀 확인이 완료되면 카드가 공개됩니다.</p><div style="height:18px"></div><button class="primary" id="studio-home">스튜디오 홈으로 이동</button></div>`; }
function render() { if (!state.authenticated) { app.innerHTML = loginView(); document.querySelector('#login-form')?.addEventListener('submit', loginArtist); return; } if (state.step === 1) shell(cardForm()); if (state.step === 2) shell(handwritingForm()); if (state.step === 3) shell(review()); if (state.step === 4) shell(complete()); if (state.step === 2) initCanvas(); }
function toast(message) { const el = document.querySelector('#toast'); if (!el) return; el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2500); }
async function api(path, options = {}) { const response = await fetch(`${API_BASE}${path}`, { ...options, credentials: 'include', headers: { ...(options.body ? { 'Content-Type': 'application/json' } : {}), ...(SESSION_TOKEN ? { 'X-Fanfolio-Session': SESSION_TOKEN } : {}), ...(options.headers || {}) } }); if (!response.ok) { const error = new Error(`API ${response.status}`); error.status = response.status; throw error; } return response.status === 204 ? null : response.json(); }
async function loginArtist(event) { event.preventDefault(); const form = new FormData(event.currentTarget); if (!state.magicLinkRequested) { const email = form.get('email')?.toString().trim(); if (!email) return; state.loginEmail = email; SESSION_TOKEN = ''; localStorage.removeItem('fanfolio_session'); try { await api('/auth/magic-link/request', { method: 'POST', body: JSON.stringify({ email, purpose: 'login' }) }); state.magicLinkRequested = true; state.loginError = `${email}로 로그인 링크를 보냈습니다.`; } catch { state.loginError = '로그인 링크를 보내지 못했습니다. 이메일과 API 상태를 확인해 주세요.'; } render(); return; } const token = form.get('token')?.toString().trim(); if (!token) return; try { await api('/auth/magic-link/verify', { method: 'POST', body: JSON.stringify({ token }) }); const result = await api('/artist/cards'); state.cards = result.data.items; state.authenticated = true; state.loginError = ''; render(); } catch (error) { SESSION_TOKEN = ''; localStorage.removeItem('fanfolio_session'); state.authenticated = false; state.loginError = error.status === 403 ? '아티스트 계정만 스튜디오에 입장할 수 있어요.' : '유효하지 않거나 만료된 로그인 링크입니다.'; render(); } }
async function loadStudio() { try { const result = await api('/artist/cards'); state.cards = result.data.items; } catch (error) { if (error.status === 401 || error.status === 403) { SESSION_TOKEN = ''; localStorage.removeItem('fanfolio_session'); state.authenticated = false; state.loginError = error.status === 403 ? '아티스트 계정만 스튜디오에 입장할 수 있어요.' : '세션이 만료됐어요. 다시 로그인해 주세요.'; render(); } } }
function bindCommon() { document.querySelector('#studio-home')?.addEventListener('click', () => { state.step = 1; state.preview = null; render(); }); document.querySelector('#logout')?.addEventListener('click', logoutArtist); document.querySelector('#session-config')?.addEventListener('click', () => { const token = window.prompt('아티스트 세션 토큰을 입력하세요.', SESSION_TOKEN); if (token !== null) { localStorage.setItem('fanfolio_session', token.trim()); window.location.reload(); } }); document.querySelector('.toggle')?.addEventListener('click', (event) => { state.form.hasVoice = !state.form.hasVoice; event.currentTarget.classList.toggle('on', state.form.hasVoice); event.currentTarget.setAttribute('aria-pressed', String(state.form.hasVoice)); }); }
async function logoutArtist() { try { await api('/auth/logout', { method: 'POST' }); } catch { /* 세션이 이미 만료된 경우에도 로컬 상태는 정리한다. */ } SESSION_TOKEN = ''; localStorage.removeItem('fanfolio_session'); state.authenticated = false; state.loginError = ''; render(); }
function initCanvas() { const canvas = document.querySelector('#signature-pad'); const context = canvas.getContext('2d'); context.strokeStyle = '#29234f'; context.lineWidth = 5; context.lineCap = 'round'; let drawing = false; const point = (event) => { const box = canvas.getBoundingClientRect(); return { x: (event.clientX - box.left) * canvas.width / box.width, y: (event.clientY - box.top) * canvas.height / box.height }; }; canvas.addEventListener('pointerdown', (event) => { drawing = true; canvas.setPointerCapture?.(event.pointerId); const p = point(event); context.beginPath(); context.moveTo(p.x, p.y); }); canvas.addEventListener('pointermove', (event) => { if (!drawing) return; const p = point(event); context.lineTo(p.x, p.y); context.stroke(); updateSignature(); }); canvas.addEventListener('pointerup', () => { drawing = false; }); document.querySelector('#clear-pad').addEventListener('click', () => { context.clearRect(0, 0, canvas.width, canvas.height); state.signature = ''; updateSignature(); }); document.querySelector('#signature-file').addEventListener('change', (event) => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const image = new Image(); image.onload = () => { context.clearRect(0, 0, canvas.width, canvas.height); context.drawImage(image, 80, 60, 600, 300); updateSignature(); }; image.src = reader.result; }; reader.readAsDataURL(file); }); document.querySelector('#remove-bg').addEventListener('click', requestBackgroundRemoval); document.querySelector('#back-card').addEventListener('click', () => { state.step = 1; render(); }); document.querySelector('#next-review').addEventListener('click', loadPreview); }
function updateSignature() { const canvas = document.querySelector('#signature-pad'); state.signature = canvas.toDataURL('image/png'); document.querySelector('#signature-result').innerHTML = `<img src="${esc(state.signature)}" alt="입력한 손글씨 미리보기" />`; }
async function uploadAsset(file, purpose) { const presigned = await api('/uploads/presign', { method: 'POST', body: JSON.stringify({ fileName: file.name, contentType: file.type, purpose }) }); const upload = await fetch(absoluteApiUrl(presigned.data.uploadUrl), { method: 'PUT', body: file, credentials: 'include', headers: { 'Content-Type': file.type, ...(SESSION_TOKEN ? { 'X-Fanfolio-Session': SESSION_TOKEN } : {}) } }); if (!upload.ok) throw new Error(`UPLOAD ${upload.status}`); return presigned.data.assetId; }
async function requestBackgroundRemoval() { const area = document.querySelector('#job-area'); area.innerHTML = '<div class="job"><span class="spinner"></span> 손글씨를 업로드하고 배경 제거를 요청하는 중...</div>'; try { const blob = await new Promise((resolve) => document.querySelector('#signature-pad').toBlob(resolve, 'image/png')); state.assetId = await uploadAsset(new File([blob], 'handwriting.png', { type: 'image/png' }), 'handwriting'); const result = await api(`/assets/${state.assetId}/background-removal`, { method: 'POST' }); state.jobId = result.data.jobId; await api(`/artist/cards/${state.cardId}`, { method: 'PATCH', body: JSON.stringify({ signatureText: state.form.signatureText, handwritingAssetId: state.assetId, handwritingTransform: { x: 68, y: 724, width: 402, rotation: -3 } }) }); area.innerHTML = `<div class="job"><span class="ok">✓</span> 작업이 등록되었습니다 · ${esc(result.data.status)}</div>`; pollBackgroundRemoval(); } catch { area.innerHTML = '<div class="notice">업로드 또는 배경 제거 요청에 실패했습니다. 아티스트 세션과 API 서버를 확인해 주세요.</div>'; } }
async function pollBackgroundRemoval() { for (let attempt = 0; attempt < 10; attempt += 1) { await new Promise((resolve) => setTimeout(resolve, 1000)); try { const result = await api(`/background-removal-jobs/${state.jobId}`); if (result.data.status === 'completed') { document.querySelector('#job-area').innerHTML = '<div class="job"><span class="ok">✓</span> 투명 손글씨가 준비되었습니다.</div>'; return; } if (result.data.status === 'failed') { document.querySelector('#job-area').innerHTML = '<div class="notice">손글씨 배경 제거에 실패했습니다. 다른 이미지를 사용해 주세요.</div>'; return; } } catch { return; } } }
async function loadPreview() { if (!state.cardId) { toast('먼저 카드 정보를 저장해 주세요.'); return; } try { const result = await api(`/artist/cards/${state.cardId}/preview`, { method: 'POST' }); state.preview = result.data; if (state.previewImageSrc) URL.revokeObjectURL(state.previewImageSrc); state.previewImageSrc = ''; if (result.data.previewImageUrl) { const image = await fetch(absoluteApiUrl(result.data.previewImageUrl), { credentials: 'include', headers: SESSION_TOKEN ? { 'X-Fanfolio-Session': SESSION_TOKEN } : {} }); if (!image.ok) throw new Error(`PREVIEW_IMAGE ${image.status}`); state.previewImageSrc = URL.createObjectURL(await image.blob()); } state.step = 3; render(); } catch { toast('카드 미리보기를 불러오지 못했습니다.'); } }
document.addEventListener('submit', async (event) => { if (event.target.id !== 'card-form') return; event.preventDefault(); const form = new FormData(event.target); const imageFile = form.get('cardImage'); state.form = { ...state.form, name: form.get('name'), memberId: form.get('memberId'), seasonName: form.get('seasonName'), templateId: form.get('templateId'), rarity: form.get('rarity'), signatureText: form.get('signatureText'), issueLimit: Number(form.get('issueLimit')) }; try { const imageAssetId = await uploadAsset(imageFile, 'card'); const result = await api('/artist/cards', { method: 'POST', body: JSON.stringify({ templateId: state.form.templateId, name: state.form.name, seasonName: state.form.seasonName, rarity: state.form.rarity, imageAssetId, memberId: state.form.memberId, signatureText: state.form.signatureText, hasVoice: state.form.hasVoice, issueLimit: state.form.issueLimit }) }); state.cardId = result.data.id; state.cardName = result.data.name; state.cards = [result.data, ...state.cards.filter((card) => card.id !== result.data.id)]; toast('카드를 임시 저장했습니다.'); state.step = 2; render(); } catch { toast('카드 이미지 업로드 또는 저장에 실패했습니다. 아티스트 세션과 API 서버를 확인해 주세요.'); } });
document.addEventListener('click', async (event) => { if (event.target.id === 'save-draft') toast('카드 정보는 다음 단계로 이동할 때 API에 저장됩니다.'); if (event.target.id === 'submit-review') { if (!state.cardId) { toast('먼저 카드 정보를 저장해 주세요.'); return; } try { await api(`/artist/cards/${state.cardId}/submit-review`, { method: 'POST' }); state.step = 4; render(); } catch { toast('검수 요청에 실패했습니다. 아티스트 세션과 API 서버를 확인해 주세요.'); } } if (event.target.id === 'back-signature') { state.step = 2; render(); } });
render();
if (state.authenticated) loadStudio();
